// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVideosFromDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function SelectDirectory():Promise<string>;
