// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDataHost(arg1) {
  return window['go']['main']['App']['AddDataHost'](arg1);
}

export function ClientStreamHandler(arg1, arg2) {
  return window['go']['main']['App']['ClientStreamHandler'](arg1, arg2);
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetVideosFromDirectory(arg1) {
  return window['go']['main']['App']['GetVideosFromDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartBackend() {
  return window['go']['main']['App']['StartBackend']();
}
