// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDataHost(arg1:Array<main.Video>):Promise<Array<string>>;

export function ClientStreamHandler(arg1:string,arg2:string):Promise<main.StreamResponse>;

export function GetVideosFromDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function SelectDirectory():Promise<string>;

export function StartBackend():Promise<void>;
